const SQUARE = "square";
const CURRENT_TURN_TEXT = "Current Turn: X";
const CURRENT_TURN_SECOND_PLAYER = "Current Turn: O";
const CURRENT_TURN_ACCESSOR = "current-turn";
let TOP_LEFT;
let TOP_CENTRE;

export {
  SQUARE,
  CURRENT_TURN_TEXT,
  CURRENT_TURN_ACCESSOR,
  CURRENT_TURN_SECOND_PLAYER,
  TOP_LEFT,
  TOP_CENTRE,
};
